version: "3"

services:
  database:
    image: mariadb:10.2.25-bionic
    container_name: "health_tools_db"
    ports:
      - "3306:3306"
    networks:
      health_tools_net:
        ipv4_address: 192.168.156.51
    volumes:
      - ./.docker/mariadb/data:/var/lib/mariadb
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: 123
    command: --default-authentication-plugin=mysql_native_password

networks:
  health_tools_net:
    ipam:
      driver: default
      config:
        - subnet: 192.168.156.0/24